name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Optional: Install dependencies and run tests
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    # - name: Run tests
    #   run: |
    #     pytest

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 3.111.20.35 >> ~/.ssh/known_hosts

    # Fix SSH key permissions and format (prevent libcrypto error)
    - name: Fix SSH key permissions
      run: |
        dos2unix ~/.ssh/id_rsa || true
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy and restart Flask app on EC2
      env:
        GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o IdentitiesOnly=yes"
      run: |
        ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes ubuntu@3.111.20.35 << 'EOF'
          cd ~/portfolio
          git pull origin main
          # If you use a virtual environment:
          # source venv/bin/activate
          # pip install -r requirements.txt
          sudo systemctl restart flaskapp.service
          exit
        EOF
