name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 3.111.20.35 >> ~/.ssh/known_hosts

      - name: Deploy and restart service on EC2
        run: |
          ssh ubuntu@3.111.20.35 "
            cd /home/ubuntu/portfolio &&
            git pull origin main &&
            sudo systemctl restart flaskapp
          "
